# Generated by Django 3.2 on 2021-04-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
